version: "3.6"
services:
  front:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    tty: true
    command: ["bash"]
  data_source:
    build:
      dockerfile: docker/Dockerfile.data_source
    tty: true
    ports:
      - "9323:9323"
    volumes:
      - ./data-source:/app
    environment:
      - DISPLAY=:10
  db:
    image: postgres:14.5-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=keiba
      - TZ="Asia/Tokyo"
    volumes:
      - data_store:/var/lib/postgresql/data
volumes:
  data_store:
